name: 'Build Workflow'
on:
  push: {}

permissions: { }

concurrency:
  group: release-group
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Build and run'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: "python -m pip install -r ./requirements.txt"
        name: "Install build dependencies"
      - run: "python -m src"
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        name: "Deploy to PRD"
        if: github.ref == 'refs/heads/develop'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: out
          NETLIFY_SITE_ID: "8c76f1f8-6ea7-437a-9ca7-8f2a7a5403fb"
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          NETLIFY_DEPLOY_MESSAGE: "GH Actions - ${{ github.sha }}"